server:
  port: 0
spring:
  output:
    ansi:
      enabled: ALWAYS
  # DataSource
  datasource:
    driver-class-name: ${REQUESTS_POSTGRESQL_DRIVER:org.postgresql.Driver}
    url: ${REQUESTS_POSTGRESQL_URL:jdbc:postgresql://localhost:5436/requests}
    username: ${REQUESTS_POSTGRESQL_USER:dbuserRequests}
    password: ${REQUESTS_POSTGRESQL_PASSWORD:12345Requests}
  # JPA
  jpa:
    hibernate:
      ddl-auto: update
  show-sql: true
  properties:
    hibernate:
      format_sql: true
      dialect: org.hibernate.dialect.PostgreSQLDialect
logging:
  level:
    ru:
      practicum: INFO
    org:
      springframework:
        orm:
          jpa: INFO
          TransactionManager: DEBUG
          transaction: INFO
          transaction.interceptor: TRACE
      Zalando:
        logbook: TRACE