server:
  port: 8080
spring:
  cloud:
    gateway:
      discovery.locator.enabled: true
      routes:
        - id: main_service_categories
          uri: lb://main-service
          predicates:
            - Path=/admin/categories/**,/categories/**

        - id: main_service_compilations
          uri: lb://main-service
          predicates:
            - Path=/admin/compilations/**,/compilations/**

        - id: main_service_comment_admin
          uri: lb://main-service
          predicates:
            - Path=/admin/comments/**

        - id: main_service_comment_private
          uri: lb://main-service
          predicates:
            - Path=/events/{eventId}/users/{userId}/comment,/users/{userId}/comment/**

        - id: main_service_comment_public
          uri: lb://main-service
          predicates:
            - Path=/events/{eventId}/comment,/comment/search

        - id: main_service_event
          uri: lb://main-service
          predicates:
            - Path=/events/**,/admin/events/**,/users/{userId}/events/**

        - id: main_service_request
          uri: lb://main-service
          predicates:
            - Path=/users/{userId}/requests/**

        - id: main_service_user
          uri: lb://main-service
          predicates:
            - Path=/admin/users/**

        - id: default_route
          uri: http://localhost:8080
          predicates:
            - Path=/**
          filters:
            - SetStatus=404