server:
  port: 0
spring:
  output:
    ansi:
      enabled: ALWAYS
  # DataSource
  datasource:
    driver-class-name: ${STATS_POSTGRESQL_DRIVER:org.postgresql.Driver}
    url: ${STATS_POSTGRESQL_URL:jdbc:postgresql://localhost:5432/stats}
    username: ${STATS_POSTGRESQL_USER:dbuserStats}
    password: ${STATS_POSTGRESQL_PASSWORD:12345Stats}
  # SQL
  sql:
    init:
      mode: always
      continue-on-error: false
      schema-locations: classpath:/DB/DDL/schema.sql
  # JPA
  jpa:
    hibernate:
      ddl-auto: update
  show-sql: true
  properties:
    hibernate:
      format_sql: true
      dialect: org.hibernate.dialect.PostgreSQLDialect
      default_schema: main
logging:
  level:
    ru:
      practicum: INFO
    org:
      springframework:
        orm:
          jpa: INFO
          TransactionManager: DEBUG
          transaction: INFO
          transaction.interceptor: TRACE
      Zalando:
        logbook: TRACE